### ISSUE TITLE
failed to reach the mAP mentioned in the paper

### ISSUE THREAD

**Issue by YZY-lucky** [JDAI-CV/fast-reid#384] opened 2021-01-17 03:49 UTC
Dear Mr. Liao, for the Veri-Wild data set of Fastreid, we have tried many times but failed to reach the mAP mentioned in the paper. The best one of mine is 5% less than yours.Would you please give me some advice on how to improve the mAP to your current level?

[ Datasets               | Rank-1   | Rank-5   | Rank-10   | mAP     | mINP   |
| -- | -- | --| --| -- | -- |
| SmallVeRiWild      | 94.85%   | 98.29%   | 99.16%    | 81.24% | 56.50% |
| MediumVeRiWild | 93.19%   | 97.57%   | 98.45%    | 75.86% | 46.80% |
| LargeVeRiWild      | 90.11%   | 95.96%   | 97.61%    | 68.37% | 35.31% |

**Comment by L1aoXingyu** [comment] 2021-01-18 05:58
Recently, the fastreid code has been refactored and changed a lot. We will try it later.

**Comment by lxc86739795** [comment] 2021-01-28 03:39
We just updated the training config on VeRi-Wild. Please try it.

**Comment by kishansairam9** [comment] 2021-03-03 01:41
Latest config (819c5a8ab4f1b36f78f9874f85e77f3ac5ea2b9a) also has the same issue.

Following was obtained with 4x 2080Ti
| Datasets       | Rank-1   | Rank-5   | Rank-10   | mAP   | mINP   | metric   |
|:---------------|:---------|:---------|:----------|:------|:-------|:---------|
| SmallVeRiWild  | 94.11    | 98.16    | 98.69     | 76.70 | 48.80  | 85.41    |
| MediumVeRiWild | 92.33    | 97.09    | 98.23     | 70.87 | 38.95  | 81.60    |
| LargeVeRiWild  | 89.30    | 95.29    | 97.09     | 63.08 | 27.81  | 76.19    |

This was obtained using 2x V100
| Datasets       | Rank-1   | Rank-5   | Rank-10   | mAP   | mINP   | metric   |
|:---------------|:---------|:---------|:----------|:------|:-------|:---------|
| SmallVeRiWild  | 94.54    | 98.36    | 99.10     | 79.45 | 53.22  | 87.00    |
| MediumVeRiWild | 93.17    | 97.41    | 98.41     | 74.08 | 43.71  | 83.63    |
| LargeVeRiWild  | 90.05    | 95.96    | 97.38     | 66.45 | 32.14  | 78.25    |

@lxc86739795

**Comment by lxc86739795** [comment] 2021-03-03 03:57
> Latest config ([819c5a8](https://github.com/JDAI-CV/fast-reid/commit/819c5a8ab4f1b36f78f9874f85e77f3ac5ea2b9a)) also has the same issue.
> 
> Following was obtained with 4x 2080Ti
> 
> Datasets	Rank-1	Rank-5	Rank-10	mAP	mINP	metric
> SmallVeRiWild	94.11	98.16	98.69	76.70	48.80	85.41
> MediumVeRiWild	92.33	97.09	98.23	70.87	38.95	81.60
> LargeVeRiWild	89.30	95.29	97.09	63.08	27.81	76.19
> This was obtained using 2x V100
> 
> Datasets	Rank-1	Rank-5	Rank-10	mAP	mINP	metric
> SmallVeRiWild	94.54	98.36	99.10	79.45	53.22	87.00
> MediumVeRiWild	93.17	97.41	98.41	74.08	43.71	83.63
> LargeVeRiWild	90.05	95.96	97.38	66.45	32.14	78.25
> @lxc86739795

This is my log file:
[veriwild_log_bagtricks_R50-ibn_4gpu.txt](https://github.com/JDAI-CV/fast-reid/files/6073483/veriwild_log_bagtricks_R50-ibn_4gpu.txt)

Line 0\~1619 is the training log. Line 1620\~end is one test procedure.
You can check the difference between your config and my config.
@kishansairam9

**Comment by lxc86739795** [comment] 2021-03-03 04:09
It seems that my latest update is not merged into the new config.
Please refer to my log file. @kishansairam9 @YZY-lucky

**Comment by kishansairam9** [comment] 2021-03-03 04:37
Thank you @lxc86739795. Main difference is in number of epochs 60 vs 120, so the difference makes sense

This is the updated config as per file you sent. I've started the training, I'll let you know once it's done.
```yaml
_BASE_: ../Base-bagtricks.yml

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

MODEL:
  BACKBONE:
    WITH_IBN: True

  HEADS:
    POOL_LAYER: gempool

  LOSSES:
    TRI:
      HARD_MINING: False
      MARGIN: 0.0

DATASETS:
  NAMES: ("VeRiWild",)
  TESTS: ("SmallVeRiWild", "MediumVeRiWild", "LargeVeRiWild",)

SOLVER:
  IMS_PER_BATCH: 128
  MAX_EPOCH: 120
  STEPS: [30, 70, 90]
  BIAS_LR_FACTOR: 1.0
  ETA_MIN_LR: 0.0000003
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 5000

  CHECKPOINT_PERIOD: 20

TEST:
  EVAL_PERIOD: 20
  IMS_PER_BATCH: 128

OUTPUT_DIR: logs/veriwild/bagtricks_R50-ibn_4gpu
```

**Comment by kishansairam9** [comment] 2021-03-04 14:10
| Datasets       | Rank-1   | Rank-5   | Rank-10   | mAP   | mINP   | metric   |
|:---------------|:---------|:---------|:----------|:------|:-------|:---------|
| SmallVeRiWild  | 95.41    | 98.66    | 99.20     | 82.93 | 59.92  | 89.17    |
| MediumVeRiWild | 93.87    | 97.93    | 98.77     | 77.69 | 50.20  | 85.78    |
| LargeVeRiWild  | 90.98    | 96.36    | 97.87     | 70.22 | 38.16  | 80.60    |

@lxc86739795  I wasn't able to reproduce results presented in MODELZOO.md using the above config. (Trained on 2x V100)

**Comment by lxc86739795** [comment] 2021-03-05 02:05
> Datasets	Rank-1	Rank-5	Rank-10	mAP	mINP	metric
> SmallVeRiWild	95.41	98.66	99.20	82.93	59.92	89.17
> MediumVeRiWild	93.87	97.93	98.77	77.69	50.20	85.78
> LargeVeRiWild	90.98	96.36	97.87	70.22	38.16	80.60
> [tensorboard_logs.zip](https://github.com/JDAI-CV/fast-reid/files/6084419/tensorboard_logs.zip)
> 
> @lxc86739795 I wasn't able to reproduce results presented in MODELZOO.md using the above config. (Trained on 2x V100)
If you use two GPUs, batch size should also be doubled, i.e., IMS_PER_BATCH: 256. This is important since it will influence sampling for Triplet Loss.

**Comment by kishansairam9** [comment] 2021-03-05 17:45
@lxc86739795  this issue can be closed!

I ran on 4x 2080 Ti, but since their RAM is limited to 12GB. I could only use IMS_PER_BATCH = 384. With this I acihieved following results, which is within 2% mAP of those presented in MODEL ZOO.md

| Datasets       | Rank-1   | Rank-5   | Rank-10   | mAP   | mINP   | metric   |
|:---------------|:---------|:---------|:----------|:------|:-------|:---------|
| SmallVeRiWild  | 96.29    | 99.06    | 99.43     | 86.43 | 66.45  | 91.36    |
| MediumVeRiWild | 95.26    | 98.33    | 98.96     | 81.75 | 57.32  | 88.51    |
| LargeVeRiWild  | 92.67    | 97.32    | 98.40     | 75.08 | 45.78  | 83.88    |

**Comment by lxc86739795** [comment] 2021-03-07 13:58
> @lxc86739795 this issue can be closed!
> 
> I ran on 4x 2080 Ti, but since their RAM is limited to 12GB. I could only use IMS_PER_BATCH = 384. With this I acihieved following results, which is within 2% mAP of those presented in MODEL ZOO.md
> 
> Datasets	Rank-1	Rank-5	Rank-10	mAP	mINP	metric
> SmallVeRiWild	96.29	99.06	99.43	86.43	66.45	91.36
> MediumVeRiWild	95.26	98.33	98.96	81.75	57.32	88.51
> LargeVeRiWild	92.67	97.32	98.40	75.08	45.78	83.88

The results are almost the same as ours except for mAPs. This may be caused by different batch sizes.

**Closed** 2021-03-07 14:08 UTC
